In [ ]:
!pip install nltk

In [ ]:
para="Narendra Damodardas Modi[a] (born 17 September 1950) is an Indian politician who has served as the prime minister of India since 2014. Modi was the chief minister of Gujarat from 2001 to 2014 and is the member of parliament (MP) for Varanasi. He is a member of the Bharatiya Janata Party (BJP) and of the Rashtriya Swayamsevak Sangh (RSS), a right-wing Hindutva paramilitary volunteer organisation. He is the longest-serving prime minister outside the Indian National Congress."


In [ ]:
import nltk
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

In [ ]:
nltk.download("punkt_tab")
nltk.download("wordnet")
nltk.download('stopwords')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
## Tokenization -- Converts paragraph-sentencess-words
import nltk
sentences = nltk.sent_tokenize(para)
print(sentences)

['Narendra Damodardas Modi[a] (born 17 September 1950) is an Indian politician who has served as the prime minister of India since 2014.', 'Modi was the chief minister of Gujarat from 2001 to 2014 and is the member of parliament (MP) for Varanasi.', 'He is a member of the Bharatiya Janata Party (BJP) and of the Rashtriya Swayamsevak Sangh (RSS), a right-wing Hindutva paramilitary volunteer organisation.', 'He is the longest-serving prime minister outside the Indian National Congress.']


In [ ]:
stemmer = PorterStemmer()
stemmer.stem("finalize")

'final'

In [ ]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
lemmatizer.lemmatize("finalizing")

'finalizing'

In [ ]:
import re
corpus = []
n=len(sentences)
print(n)
for i in range(n):
  review =  re.sub("[^a-zA-Z]"," ",sentences[i])
  review=review.lower()
  corpus.append(review)
print(corpus)

4
['narendra damodardas modi a   born    september       is an indian politician who has served as the prime minister of india since      ', 'modi was the chief minister of gujarat from      to      and is the member of parliament  mp  for varanasi ', 'he is a member of the bharatiya janata party  bjp  and of the rashtriya swayamsevak sangh  rss   a right wing hindutva paramilitary volunteer organisation ', 'he is the longest serving prime minister outside the indian national congress ']


In [ ]:
len(stopwords.words("english"))

198

In [ ]:
## Stemming
for i in range(n):
  words = nltk.word_tokenize(corpus[i])
  words = [stemmer.stem(word) for word in words if word not in set(stopwords.words("english"))]
  corpus[i] = " ".join(words)
print(corpus)

['narendra damodarda modi born septemb indian politician serv prime minist india sinc', 'modi chief minist gujarat member parliament mp varanasi', 'member bharatiya janata parti bjp rashtriya swayamsevak sangh rss right wing hindutva paramilitari volunt organis', 'longest serv prime minist outsid indian nation congress']


In [ ]:
## Lemmatization
for i in range(n):
  words = nltk.word_tokenize(corpus[i])
  words = [lemmatizer.lemmatize(word) for word in words if word not in set(stopwords.words("english"))]
  corpus[i] = " ".join(words)
print(corpus)

['narendra damodarda modi born septemb indian politician serv prime minist india sinc', 'modi chief minist gujarat member parliament mp varanasi', 'member bharatiya janata parti bjp rashtriya swayamsevak sangh rss right wing hindutva paramilitari volunt organis', 'longest serv prime minist outsid indian nation congress']


In [ ]:
#Bag Of words
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(3,3))

In [ ]:
x = cv.fit_transform(corpus)
x[0].toarray()

array([[0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
        0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0]])

In [ ]:
cv.vocabulary_

{'narendra damodarda modi': 18,
 'damodarda modi born': 4,
 'modi born septemb': 16,
 'born septemb indian': 2,
 'septemb indian politician': 30,
 'indian politician serv': 8,
 'politician serv prime': 23,
 'serv prime minist': 31,
 'prime minist india': 24,
 'minist india sinc': 14,
 'modi chief minist': 17,
 'chief minist gujarat': 3,
 'minist gujarat member': 13,
 'gujarat member parliament': 5,
 'member parliament mp': 12,
 'parliament mp varanasi': 21,
 'member bharatiya janata': 11,
 'bharatiya janata parti': 0,
 'janata parti bjp': 9,
 'parti bjp rashtriya': 22,
 'bjp rashtriya swayamsevak': 1,
 'rashtriya swayamsevak sangh': 26,
 'swayamsevak sangh rss': 32,
 'sangh rss right': 29,
 'rss right wing': 28,
 'right wing hindutva': 27,
 'wing hindutva paramilitari': 33,
 'hindutva paramilitari volunt': 6,
 'paramilitari volunt organis': 20,
 'longest serv prime': 10,
 'prime minist outsid': 25,
 'minist outsid indian': 15,
 'outsid indian nation': 19,
 'indian nation congress': 7}

##**TF-IDF**

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
cv1 = TfidfVectorizer(ngram_range=(3,3),max_features=3) #Takes top 3 if less than three are present
x=cv1.fit_transform(corpus)
x[0].toarray()

array([[0.        , 0.78528828, 0.6191303 ]])

In [ ]:
cv1.vocabulary_

{'born septemb indian': np.int64(1),
 'serv prime minist': np.int64(2),
 'bharatiya janata parti': np.int64(0)}

#**Word2Vec**

In [ ]:
import gensim

In [ ]:
import gensim.downloader as api
vec_king = wv["king"] #Uses Cosine Similarity
vec_king.shape

(300,)

In [ ]:
wv.similarity("man","king")

0.22942673

In [ ]:
wv.similarity("html","programmer")

0.25811526

In [ ]:
wv.most_similar("cricket")

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783)]

In [ ]:
wv.similarity("cricket","sports")

0.40087253

In [ ]:
vec = wv["king"]-wv["man"]+wv["woman"]
wv.most_similar([vec])

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289887189865112)]

#**WORD2VEC AND AVGWORD2VEC**

In [ ]:
# Importing the dataset

import pandas as pd
messages = pd.read_csv("/content/SMSSpamCollection.txt",sep="\t",names=["label","message"])
messages.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
messages.shape

(5572, 2)

In [ ]:
messages["message"].loc[100]

"Please don't text me anymore. I have nothing else to say."

In [ ]:
# Data Cleaning and Preprocessing
import re
import nltk
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [ ]:
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^0-9a-zA-Z]', ' ', messages['message'][i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [ ]:
corpus[1:4]

['ok lar joke wif u oni',
 'free entri 2 wkli comp win fa cup final tkt 21st may 2005 text fa 87121 receiv entri question std txt rate c appli 08452810075over18',
 'u dun say earli hor u c alreadi say']

In [ ]:
# Creating the Bag of Words Model
from sklearn.feature_extraction.text import CountVectorizer
cv =  CountVectorizer(max_features=2500,binary=True,ngram_range=(2,2))
x = cv.fit_transform(corpus).toarray()
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
x.shape

(5572, 2500)

In [ ]:
# Label Encoding
y =pd.get_dummies(messages["label"],dtype=int)
y=y.iloc[:,1].values
y

array([0, 0, 1, ..., 0, 0, 0])

In [ ]:
# Train Test Split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(4457, 2500)
(1115, 2500)
(4457,)
(1115,)


In [ ]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(x_train,y_train)

In [ ]:
# Prediction
y_prec = spam_detect_model.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_prec))
print(classification_report(y_test,y_prec))

0.9721973094170404
              precision    recall  f1-score   support

           0       0.97      1.00      0.98       955
           1       1.00      0.81      0.89       160

    accuracy                           0.97      1115
   macro avg       0.98      0.90      0.94      1115
weighted avg       0.97      0.97      0.97      1115



In [ ]:
# Creating the TFIDF model
from sklearn.feature_extraction.text import TfidfVectorizer
cv =  TfidfVectorizer(max_features=2500,ngram_range=(1,2))
x = cv.fit_transform(corpus).toarray()
x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
# Train Test Split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
# Train Test Split
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(x_train,y_train)

In [ ]:
#Prediction
y_prec = spam_detect_model.predict(x_test)

In [ ]:
score = accuracy_score(y_test,y_prec)
print(score)

0.9811659192825112


In [ ]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

In [ ]:
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['message'][i])
    review = review.lower()
    review = review.split()

    review = [lemmatizer.lemmatize(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [ ]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [ ]:
words=[]
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))
words

[['go',
  'jurong',
  'point',
  'crazy',
  'available',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'wkly',
  'comp',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply'],
 ['dun', 'say', 'early', 'hor', 'already', 'say'],
 ['nah', 'think', 'go', 'usf', 'life', 'around', 'though'],
 ['freemsg',
  'hey',
  'darling',
  'week',
  'word',
  'back',
  'like',
  'fun',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'send',
  'rcv'],
 ['even', 'brother', 'like', 'speak', 'treat', 'like', 'aid', 'patent'],
 ['per',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'set',
  'callertune',
  'caller',
  'press',
  'copy',
  'friend',
  'callertune'],
 ['winner',
  'valued',
  'network',
  'customer',
  'selected',
  'receivea',
 

In [ ]:
import gensim

In [ ]:
# Lets train Word2Vec from Scratch
model = gensim.models.Word2Vec(words,window=5,min_count=2)
# model.wv.index_to_key

In [ ]:
model.corpus_count

5564

In [ ]:
model.epochs

5

In [ ]:
model.wv.similar_by_word("prize")

[('call', 0.9993091225624084),
 ('claim', 0.9992731213569641),
 ('line', 0.9992249011993408),
 ('cash', 0.9991476535797119),
 ('show', 0.9991262555122375),
 ('draw', 0.9991105794906616),
 ('free', 0.9990437626838684),
 ('mobile', 0.9990124106407166),
 ('service', 0.9989584684371948),
 ('txt', 0.9989182353019714)]

In [ ]:
def avg_word2vec(doc):
   # remove out-of-vocabulary words
    #sent = [word for word in doc if word in model.wv.index_to_key]
    #print(sent)
    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis=0)
                #or [np.zeros(len(model.wv.index_to_key))], axis=0)

In [ ]:
import numpy as np

In [ ]:
from tqdm import tqdm

In [ ]:
#apply for the entire sentences
X=[]
for i in tqdm(range(len(words))):
    # print("Hello",i)
    X.append(avg_word2vec(words[i]))

  0%|          | 0/5564 [00:00<?, ?it/s]/usr/local/lib/python3.11/dist-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.11/dist-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
100%|██████████| 5564/5564 [00:00<00:00, 6015.75it/s]


In [ ]:
X[0].shape

(100,)

### Word Embedding Techniques using Embedding Layer in Keras

In [ ]:
# !pip install tensorflow==2.12.0

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
### Sentences
sent=['the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
]

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words']

In [ ]:
## Vocabulary_size= 10000
vocsize=10000

One hot Encoding

In [ ]:
onehot = [one_hot(words,vocsize) for words in sent]
print(onehot)

[[5796, 6467, 2992, 3836], [5796, 6467, 2992, 7436], [5796, 1204, 2992, 7561], [2984, 6281, 8873, 2530, 3428], [2984, 6281, 8873, 2530, 7476], [5721, 5796, 4272, 2992, 9288]]


In [ ]:
#Post padding and prepadding should be used for the length of a sentence to be same
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential


In [ ]:
import numpy as np

In [ ]:
#Pre Padding
# We can also use post padding
sent_length = 8
embedded_docs=pad_sequences(onehot,padding="pre",maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5796 6467 2992 3836]
 [   0    0    0    0 5796 6467 2992 7436]
 [   0    0    0    0 5796 1204 2992 7561]
 [   0    0    0 2984 6281 8873 2530 3428]
 [   0    0    0 2984 6281 8873 2530 7476]
 [   0    0    0 5721 5796 4272 2992 9288]]


In [ ]:
dim=10

In [ ]:
model = Sequential()
model.add(Embedding(vocsize,10,input_length=sent_length))
model.compile("adam","mse")

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0, 5796, 6467, 2992, 3836], dtype=int32)

In [ ]:
model.predict(embedded_docs[0])
# each word  in a sentence is represented in 10 dimensions

1/1 [==============================] - 0s 31ms/step


array([[ 0.04678542, -0.03756585, -0.03486269, -0.04651045,  0.0463591 ,
         0.00307266, -0.00468531, -0.03418862,  0.01814603, -0.03368761],
       [ 0.04678542, -0.03756585, -0.03486269, -0.04651045,  0.0463591 ,
         0.00307266, -0.00468531, -0.03418862,  0.01814603, -0.03368761],
       [ 0.04678542, -0.03756585, -0.03486269, -0.04651045,  0.0463591 ,
         0.00307266, -0.00468531, -0.03418862,  0.01814603, -0.03368761],
       [ 0.04678542, -0.03756585, -0.03486269, -0.04651045,  0.0463591 ,
         0.00307266, -0.00468531, -0.03418862,  0.01814603, -0.03368761],
       [ 0.0379588 ,  0.01206845,  0.03082493,  0.01040367,  0.01757891,
        -0.02975464, -0.01399621, -0.00913811,  0.00900797,  0.0483053 ],
       [-0.043252  , -0.01469547,  0.04713554, -0.01872214, -0.03735572,
        -0.04775465, -0.00219639, -0.00760516, -0.03005166, -0.02428352],
       [-0.02238002, -0.02548686,  0.03047996, -0.03676445, -0.04339045,
         0.02117333,  0.0092878 , -0.04059505

FAKE NEWS CLASSIFIER USING LSTM

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/train.csv", on_bad_lines='skip', engine='python')
df.head()

id                                              title              author  \
0  0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1  1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2  2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3  3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4  4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...     1  
1  Ever get the feeling your life circles the rou...     0  
2  Why the Truth Might Get You Fired October 29, ...     1  
3  Videos 15 Civilians Killed In Single US Airstr...     1  
4  Print \nAn Iranian woman has been sentenced to...     1

In [ ]:
df.shape

(20822, 5)

In [ ]:
df.size

104110

In [ ]:
df.isnull().sum()

id           0
title      565
author    1975
text        59
label       22
dtype: int64

In [ ]:
###Drop Nan Values
df=df.dropna()
df.shape

(18285, 5)

In [ ]:
## Get the Independent Features
x=df.drop("label",axis=1)

In [ ]:
## Get the Dependent features
y=df['label']

In [ ]:
y.shape

(18285,)

In [ ]:
import tensorflow as tf
tf.__version__

'2.18.0'

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

One hot Representation

In [ ]:
messages = x.copy()
messages

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20817  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20818  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20819  20797  Macy’s Is Said to Receive Takeover Approach by...   
20820  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20821  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20817                              Jerome Hudson   
20818                           Benjamin Hoffman   
20819  Michael J. de la Merced and Rachel Abrams   
20820                                Alex Ansary   
20821                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20817  Rapper T. I. unloaded on black celebrities who...  
20818  When the Green Bay Packers lost to the Washing...  
20819  The Macy’s of today grew from the union of sev...  
20820  NATO, Russia To Hold Parallel Exercises In Bal...  
20821    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [ ]:
import nltk
import re
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
import re

ps = PorterStemmer()
corpus = []

for i in range(0, len(messages)):
    text = messages['title'].iloc[i]  # safer than messages['title'][i]
    review = re.sub('[^a-zA-Z]', ' ', text)
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if word not in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)


In [ ]:
voc_size=100000
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[51996, 70959, 91890, 37796, 57015, 79570, 33351, 83569, 1866, 46530],
 [68127, 16228, 80843, 6199, 17203, 22249, 65039],
 [57143, 73898, 66910, 98303],
 [10857, 99670, 56692, 75802, 24431, 26716],
 [81439, 17203, 10063, 76502, 86957, 10416, 17203, 4651, 63707, 74889],
 [75102,
  31071,
  47471,
  14085,
  5366,
  33053,
  71526,
  7290,
  45152,
  25893,
  62375,
  16812,
  48817,
  13032,
  65039],
 [42791, 15818, 68969, 96810, 89778, 45329, 66273, 92760, 46833, 80585, 13887],
 [38149, 22567, 94249, 97290, 7826, 44638, 33053, 74984, 46833, 80585, 13887],
 [81581, 9450, 73589, 43706, 82491, 2336, 3215, 50955, 33053, 64239],
 [72940, 33119, 41257, 39823, 67165, 2096, 65043, 7936],
 [75022, 96356, 12445, 52724, 98187, 43843, 42713, 21007, 6231, 86766, 90463],
 [75802, 42300, 57015, 2336, 33053, 7826],
 [15001, 2200, 29123, 61862, 54712, 61588, 76370, 89594, 47017],
 [56151, 96075, 5097, 3251, 69554, 46941, 6439, 46833, 80585, 13887],
 [33617, 87790, 31317, 84291, 37227, 46833, 80585, 1

Embedding Representation

In [ ]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[51996 70959 91890 ...     0     0     0]
 [68127 16228 80843 ...     0     0     0]
 [57143 73898 66910 ...     0     0     0]
 ...
 [53664 40671 59553 ...     0     0     0]
 [19256  7826 85779 ...     0     0     0]
 [42646 33827 50234 ...     0     0     0]]


In [ ]:
## Creating model
embedding_vector_features=40 ##features representation
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_2 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [ ]:
len(embedded_docs),y.shape

(18285, (18285,))

In [ ]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

### Model Training

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [ ]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

### Performance Metrics And Accuracy

In [ ]:
y_pred=model.predict(X_test)

189/189 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step


In [ ]:
y_pred=np.where(y_pred > 0.6, 1,0) ##AUC ROC Curve

## Fake News Classificer Using Bidirectional LSTM

In [ ]:
## Dataset: https://www.kaggle.com/competitions/fake-news/data?select=train.csv
import pandas as pd

In [ ]:
df=pd.read_csv('train.csv',engine='python',on_bad_lines='skip')

In [ ]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [ ]:
df.isnull().sum()

id         0
title     14
author    69
text       2
label      0
dtype: int64

In [ ]:
df.shape

(595, 5)

In [ ]:
df=df.dropna()

In [ ]:
df.head()

In [ ]:
## get the independent features
X=df.drop('label',axis=1)

In [ ]:
y=df['label']

In [ ]:
## Check whether dataset is balanced or not
y.value_counts()

label
0    298
1    214
Name: count, dtype: int64

In [ ]:
import tensorflow as tf
tf.__version__

'2.18.0'

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional


In [ ]:
## vocabulary size
voc_size=5000

In [ ]:
messages=X.copy()

In [ ]:
messages.head(10)

id                                              title  \
0    0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1    1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2    2                  Why the Truth Might Get You Fired   
3    3  15 Civilians Killed In Single US Airstrike Hav...   
4    4  Iranian woman jailed for fictional unpublished...   
5    5  Jackie Mason: Hollywood Would Love Trump if He...   
7    7  Benoît Hamon Wins French Socialist Party’s Pre...   
9    9  A Back-Channel Plan for Ukraine and Russia, Co...   
10  10  Obama’s Organizing for Action Partners with So...   
11  11  BBC Comedy Sketch "Real Housewives of ISIS" Ca...   

                          author  \
0                  Darrell Lucus   
1                Daniel J. Flynn   
2             Consortiumnews.com   
3                Jessica Purkiss   
4                 Howard Portnoy   
5                Daniel Nussbaum   
7                Alissa J. Rubin   
9   Megan Twohey and Scott Shane   
10                   Aaron Klein   
11               Chris Tomlinson   

                                                 text  
0   House Dem Aide: We Didn’t Even See Comey’s Let...  
1   Ever get the feeling your life circles the rou...  
2   Why the Truth Might Get You Fired October 29, ...  
3   Videos 15 Civilians Killed In Single US Airstr...  
4   Print \nAn Iranian woman has been sentenced to...  
5   In these trying times, Jackie Mason is the Voi...  
7   PARIS  —   France chose an idealistic, traditi...  
9   A week before Michael T. Flynn resigned as nat...  
10  Organizing for Action, the activist group that...  
11  The BBC produced spoof on the “Real Housewives...

In [ ]:
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
from nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords
import re

ps = PorterStemmer()
corpus = []

for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['title'].iloc[i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if word not in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [ ]:
onehot_repr=[one_hot(words,voc_size) for words in corpus]
onehot_repr

[[1499, 2986, 2286, 3200, 4771, 2064, 3285, 130, 4496, 1752],
 [2519, 3820, 1557, 3486, 4504, 2656, 956],
 [3494, 4000, 4819, 3945],
 [72, 4529, 2763, 2158, 4392, 3739],
 [4817, 4504, 2456, 3258, 4563, 3939, 4504, 504, 4039, 666],
 [2687,
  4420,
  4483,
  1177,
  4493,
  3910,
  4434,
  2957,
  4596,
  4525,
  1663,
  4039,
  4717,
  2508,
  956],
 [2566, 1768, 2159, 3646, 637, 2427, 2609, 1251, 3053, 1280, 3548],
 [562, 1661, 4070, 4398, 3673, 3990, 3910, 993, 3053, 1280, 3548],
 [2159, 2751, 1409, 4367, 4522, 2836, 4296, 3504, 3910, 4636],
 [1878, 4684, 1103, 3486, 3464, 1403, 4188, 861],
 [3670, 1171, 4010, 778, 359, 2743, 482, 1143, 2358, 2013, 4595],
 [2158, 4873, 4771, 2836, 3910, 3673],
 [4422, 532, 3746, 2451, 308, 2013, 4374, 4422, 296],
 [2508, 922, 2422, 3437, 1368, 704, 3801, 3053, 1280, 3548],
 [2172, 4369, 698, 4700, 2155, 3053, 1280, 3548],
 [553, 4145, 1989, 1753, 989, 1697, 1248, 2807, 1667, 2539],
 [920, 1941, 3820],
 [3018, 2586, 4962, 3567, 3910, 4281, 1500, 956],


In [ ]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
embedded_docs

array([[   0,    0,    0, ...,  130, 4496, 1752],
       [   0,    0,    0, ..., 4504, 2656,  956],
       [   0,    0,    0, ..., 4000, 4819, 3945],
       ...,
       [   0,    0,    0, ..., 2862, 1911,  787],
       [   0,    0,    0, ..., 3053, 1280, 3548],
       [   0,    0,    0, ..., 1978, 4407, 2791]], dtype=int32)

In [ ]:
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Bidirectional(LSTM(100)))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [ ]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [ ]:
## train test split

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [ ]:
## Model Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=32)

In [ ]:
y_pred=model.predict(X_test)

6/6 ━━━━━━━━━━━━━━━━━━━━ 3s 49ms/step


In [ ]:
import numpy as np

y_pred=np.where(y_pred>=0.5,1,0)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
confusion_matrix(y_test,y_pred)

array([[97,  4],
       [63,  5]])

In [ ]:
print(accuracy_score(y_test,y_pred))

0.6035502958579881
